{% set name = "napari-boxmanager" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_boxmanager-{{ version }}.tar.gz
  sha256: fb583a6a68884ba132f5921b796f8cc82c0299867c0fd6352cb2d5aa81dda694

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools-scm
  run:
    - matplotlib-base
    - mrcfile
    - napari >=0.4.17
    - numpy <=1.23.5   # https://github.com/napari/napari/issues/5484, should be fixed in the next napari release
    - pandas
    - pystardb >=0.4.2
    - python >=3.10
    - qtpy
    - scipy
    - tifffile
    - tqdm

test:
  imports:
    - box_manager
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-boxmanager
  summary: Particle selection tool for cryo-em
  license: MPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/MPI-Dortmund/napari-boxmanager

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - mstabrin
